export const chartList = [
  { title: 'chart1', content: 'chartTest1', id: 'ch1' },
  { title: 'chart2', content: 'chartTest2', id: 'ch2' },
  { title: 'chart3', content: 'chartTest3', id: 'ch3' },
  { title: 'chart4', content: 'chartTest4', id: 'ch4' },
  { title: 'chart5', content: 'chartTest5', id: 'ch5' },
  { title: 'chart6', content: 'chartTest6', id: 'ch6' },
  { title: 'chart7', content: 'chartTest7', id: 'ch7' },
  { title: 'chart8', content: 'chartTest8', id: 'ch8' },

  { title: 'chart9', content: 'chartTest9', id: 'ch9' },
  { title: 'chart10', content: 'chartTest10', id: 'ch10' },
  { title: 'chart11', content: 'chartTest11', id: 'ch11' },
  { title: 'chart12', content: 'chartTest12', id: 'ch12' },
  { title: 'chart13', content: 'chartTest13', id: 'ch13' },
  { title: 'chart14', content: 'chartTest14', id: 'ch14' },
  { title: 'chart15', content: 'chartTest15', id: 'ch15' },
  { title: 'chart16', content: 'chartTest16', id: 'ch16' },

  { title: 'chart17', content: 'chartTest17', id: 'ch17' },
  { title: 'chart18', content: 'chartTest18', id: 'ch18' },
  { title: 'chart19', content: 'chartTest19', id: 'ch19' },
  { title: 'chart20', content: 'chartTest20', id: 'ch20' },
  { title: 'chart21', content: 'chartTest21', id: 'ch21' },
  { title: 'chart22', content: 'chartTest22', id: 'ch22' },
  { title: 'chart23', content: 'chartTest23', id: 'ch23' },
  { title: 'chart24', content: 'chartTest24', id: 'ch24' },

  { title: 'chart25', content: 'chartTest25', id: 'ch25' },
  { title: 'chart26', content: 'chartTest26', id: 'ch26' },
  { title: 'chart27', content: 'chartTest27', id: 'ch27' },
  { title: 'chart28', content: 'chartTest28', id: 'ch28' },
  { title: 'chart29', content: 'chartTest29', id: 'ch29' },
  { title: 'chart30', content: 'chartTest30', id: 'ch30' },
  { title: 'chart31', content: 'chartTest31', id: 'ch31' },
  { title: 'chart32', content: 'chartTest32', id: 'ch32' },

  { title: 'chart33', content: 'chartTest33', id: 'ch33' },
  { title: 'chart34', content: 'chartTest34', id: 'ch34' },
  { title: 'chart35', content: 'chartTest35', id: 'ch35' },
];

export const whookList = [
  { title: 'whook1', content: 'whookTest1', id: 'wh1' },
  { title: 'whook2', content: 'whookTest2', id: 'wh2' },
  { title: 'whook3', content: 'whookTest3', id: 'wh3' },
  { title: 'whook4', content: 'whookTest4', id: 'wh4' },
  { title: 'whook5', content: 'whookTest5', id: 'wh5' },
  { title: 'whook6', content: 'whookTest6', id: 'wh6' },
  { title: 'whook7', content: 'whookTest7', id: 'wh7' },
  { title: 'whook8', content: 'whookTest8', id: 'wh8' },

  { title: 'whook9', content: 'whookTest9', id: 'wh9' },
  { title: 'whook10', content: 'whookTest10', id: 'wh10' },
  { title: 'whook11', content: 'whookTest11', id: 'wh11' },
  { title: 'whook12', content: 'whookTest12', id: 'wh12' },
  { title: 'whook13', content: 'whookTest13', id: 'wh13' },
  { title: 'whook14', content: 'whookTest14', id: 'wh14' },
  { title: 'whook15', content: 'whookTest15', id: 'wh15' },
  { title: 'whook16', content: 'whookTest16', id: 'wh16' },

  { title: 'whook17', content: 'whookTest17', id: 'wh17' },
  { title: 'whook18', content: 'whookTest18', id: 'wh18' },
  { title: 'whook19', content: 'whookTest19', id: 'wh19' },
  { title: 'whook20', content: 'whookTest20', id: 'wh20' },
  { title: 'whook21', content: 'whookTest21', id: 'wh21' },
  { title: 'whook22', content: 'whookTest22', id: 'wh22' },
  { title: 'whook23', content: 'whookTest23', id: 'wh23' },
  { title: 'whook24', content: 'whookTest24', id: 'wh24' },

  { title: 'whook25', content: 'whookTest25', id: 'wh25' },
  { title: 'whook26', content: 'whookTest26', id: 'wh26' },
  { title: 'whook27', content: 'whookTest27', id: 'wh27' },
  { title: 'whook28', content: 'whookTest28', id: 'wh28' },
  { title: 'whook29', content: 'whookTest29', id: 'wh29' },
  { title: 'whook30', content: 'whookTest30', id: 'wh30' },
  { title: 'whook31', content: 'whookTest31', id: 'wh31' },
  { title: 'whook32', content: 'whookTest32', id: 'wh32' },

  { title: 'whook33', content: 'whookTest33', id: 'wh33' },
  { title: 'whook34', content: 'whookTest34', id: 'wh34' },
  { title: 'whook35', content: 'whookTest35', id: 'wh35' },
];

export const eventList = [
  { title: 'event1', content: 'eventTest1', id: 'ev1' },
  { title: 'event2', content: 'eventTest2', id: 'ev2' },
  { title: 'event3', content: 'eventTest3', id: 'ev3' },
  { title: 'event4', content: 'eventTest4', id: 'ev4' },
  { title: 'event5', content: 'eventTest5', id: 'ev5' },
  { title: 'event6', content: 'eventTest6', id: 'ev6' },
  { title: 'event7', content: 'eventTest7', id: 'ev7' },
  { title: 'event8', content: 'eventTest8', id: 'ev8' },

  { title: 'event9', content: 'eventTest9', id: 'ev9' },
  { title: 'event10', content: 'eventTest10', id: 'ev10' },
  { title: 'event11', content: 'eventTest11', id: 'ev11' },
  { title: 'event12', content: 'eventTest12', id: 'ev12' },
  { title: 'event13', content: 'eventTest13', id: 'ev13' },
  { title: 'event14', content: 'eventTest14', id: 'ev14' },
  { title: 'event15', content: 'eventTest15', id: 'ev15' },
  { title: 'event16', content: 'eventTest16', id: 'ev16' },

  { title: 'event17', content: 'eventTest17', id: 'ev17' },
  { title: 'event18', content: 'eventTest18', id: 'ev18' },
  { title: 'event19', content: 'eventTest19', id: 'ev19' },
  { title: 'event20', content: 'eventTest20', id: 'ev20' },
  { title: 'event21', content: 'eventTest21', id: 'ev21' },
  { title: 'event22', content: 'eventTest22', id: 'ev22' },
  { title: 'event23', content: 'eventTest23', id: 'ev23' },
  { title: 'event24', content: 'eventTest24', id: 'ev24' },

  { title: 'event25', content: 'eventTest25', id: 'ev25' },
  { title: 'event26', content: 'eventTest26', id: 'ev26' },
  { title: 'event27', content: 'eventTest27', id: 'ev27' },
  { title: 'event28', content: 'eventTest28', id: 'ev28' },
  { title: 'event29', content: 'eventTest29', id: 'ev29' },
  { title: 'event30', content: 'eventTest30', id: 'ev30' },
  { title: 'event31', content: 'eventTest31', id: 'ev31' },
  { title: 'event32', content: 'eventTest32', id: 'ev32' },

  { title: 'event33', content: 'eventTest33', id: 'ev33' },
  { title: 'event34', content: 'eventTest34', id: 'ev34' },
  { title: 'event35', content: 'eventTest35', id: 'ev35' },
];

export const newsList = [
  { title: 'news1', content: 'newsTest1', id: 'ne1' },
  { title: 'news2', content: 'newsTest2', id: 'ne2' },
  { title: 'news3', content: 'newsTest3', id: 'ne3' },
  { title: 'news4', content: 'newsTest4', id: 'ne4' },
  { title: 'news5', content: 'newsTest5', id: 'ne5' },
  { title: 'news6', content: 'newsTest6', id: 'ne6' },
  { title: 'news7', content: 'newsTest7', id: 'ne7' },
  { title: 'news8', content: 'newsTest8', id: 'ne8' },

  { title: 'news9', content: 'newsTest9', id: 'ne9' },
  { title: 'news10', content: 'newsTest10', id: 'ne10' },
  { title: 'news11', content: 'newsTest11', id: 'ne11' },
  { title: 'news12', content: 'newsTest12', id: 'ne12' },
  { title: 'news13', content: 'newsTest13', id: 'ne13' },
  { title: 'news14', content: 'newsTest14', id: 'ne14' },
  { title: 'news15', content: 'newsTest15', id: 'ne15' },
  { title: 'news16', content: 'newsTest16', id: 'ne16' },

  { title: 'news17', content: 'newsTest17', id: 'ne17' },
  { title: 'news18', content: 'newsTest18', id: 'ne18' },
  { title: 'news19', content: 'newsTest19', id: 'ne19' },
  { title: 'news20', content: 'newsTest20', id: 'ne20' },
  { title: 'news21', content: 'newsTest21', id: 'ne21' },
  { title: 'news22', content: 'newsTest22', id: 'ne22' },
  { title: 'news23', content: 'newsTest23', id: 'ne23' },
  { title: 'news24', content: 'newsTest24', id: 'ne24' },

  { title: 'news25', content: 'newsTest25', id: 'ne25' },
  { title: 'news26', content: 'newsTest26', id: 'ne26' },
  { title: 'news27', content: 'newsTest27', id: 'ne27' },
  { title: 'news28', content: 'newsTest28', id: 'ne28' },
  { title: 'news29', content: 'newsTest29', id: 'ne29' },
  { title: 'news30', content: 'newsTest30', id: 'ne30' },
  { title: 'news31', content: 'newsTest31', id: 'ne31' },
  { title: 'news32', content: 'newsTest32', id: 'ne32' },

  { title: 'news33', content: 'newsTest33', id: 'ne33' },
  { title: 'news34', content: 'newsTest34', id: 'ne34' },
  { title: 'news35', content: 'newsTest35', id: 'ne35' },
];

export const storeList = [
  { title: 'store1', content: 'storeTest1', id: 'st1' },
  { title: 'store2', content: 'storeTest2', id: 'st2' },
  { title: 'store3', content: 'storeTest3', id: 'st3' },
  { title: 'store4', content: 'storeTest4', id: 'st4' },
  { title: 'store5', content: 'storeTest5', id: 'st5' },
  { title: 'store6', content: 'storeTest6', id: 'st6' },
  { title: 'store7', content: 'storeTest7', id: 'st7' },
  { title: 'store8', content: 'storeTest8', id: 'st8' },

  { title: 'store9', content: 'storeTest9', id: 'st9' },
  { title: 'store10', content: 'storeTest10', id: 'st10' },
  { title: 'store11', content: 'storeTest11', id: 'st11' },
  { title: 'store12', content: 'storeTest12', id: 'st12' },
  { title: 'store13', content: 'storeTest13', id: 'st13' },
  { title: 'store14', content: 'storeTest14', id: 'st14' },
  { title: 'store15', content: 'storeTest15', id: 'st15' },
  { title: 'store16', content: 'storeTest16', id: 'st16' },

  { title: 'store17', content: 'storeTest17', id: 'st17' },
  { title: 'store18', content: 'storeTest18', id: 'st18' },
  { title: 'store19', content: 'storeTest19', id: 'st19' },
  { title: 'store20', content: 'storeTest20', id: 'st20' },
  { title: 'store21', content: 'storeTest21', id: 'st21' },
  { title: 'store22', content: 'storeTest22', id: 'st22' },
  { title: 'store23', content: 'storeTest23', id: 'st23' },
  { title: 'store24', content: 'storeTest24', id: 'st24' },

  { title: 'store25', content: 'storeTest25', id: 'st25' },
  { title: 'store26', content: 'storeTest26', id: 'st26' },
  { title: 'store27', content: 'storeTest27', id: 'st27' },
  { title: 'store28', content: 'storeTest28', id: 'st28' },
  { title: 'store29', content: 'storeTest29', id: 'st29' },
  { title: 'store30', content: 'storeTest30', id: 'st30' },
  { title: 'store31', content: 'storeTest31', id: 'st31' },
  { title: 'store32', content: 'storeTest32', id: 'st32' },

  { title: 'store33', content: 'storeTest33', id: 'st33' },
  { title: 'store34', content: 'storeTest34', id: 'st34' },
  { title: 'store35', content: 'storeTest35', id: 'st35' },
];

export const chargeList = [
  { title: 'charge1', content: 'chargeTest1', id: 'cg1' },
  { title: 'charge2', content: 'chargeTest2', id: 'cg2' },
  { title: 'charge3', content: 'chargeTest3', id: 'cg3' },
  { title: 'charge4', content: 'chargeTest4', id: 'cg4' },
  { title: 'charge5', content: 'chargeTest5', id: 'cg5' },
  { title: 'charge6', content: 'chargeTest6', id: 'cg6' },
  { title: 'charge7', content: 'chargeTest7', id: 'cg7' },
  { title: 'charge8', content: 'chargeTest8', id: 'cg8' },

  { title: 'charge9', content: 'chargeTest9', id: 'cg9' },
  { title: 'charge10', content: 'chargeTest10', id: 'cg10' },
  { title: 'charge11', content: 'chargeTest11', id: 'cg11' },
  { title: 'charge12', content: 'chargeTest12', id: 'cg12' },
  { title: 'charge13', content: 'chargeTest13', id: 'cg13' },
  { title: 'charge14', content: 'chargeTest14', id: 'cg14' },
  { title: 'charge15', content: 'chargeTest15', id: 'cg15' },
  { title: 'charge16', content: 'chargeTest16', id: 'cg16' },

  { title: 'charge17', content: 'chargeTest17', id: 'cg17' },
  { title: 'charge18', content: 'chargeTest18', id: 'cg18' },
  { title: 'charge19', content: 'chargeTest19', id: 'cg19' },
  { title: 'charge20', content: 'chargeTest20', id: 'cg20' },
  { title: 'charge21', content: 'chargeTest21', id: 'cg21' },
  { title: 'charge22', content: 'chargeTest22', id: 'cg22' },
  { title: 'charge23', content: 'chargeTest23', id: 'cg23' },
  { title: 'charge24', content: 'chargeTest24', id: 'cg24' },

  { title: 'charge25', content: 'chargeTest25', id: 'cg25' },
  { title: 'charge26', content: 'chargeTest26', id: 'cg26' },
  { title: 'charge27', content: 'chargeTest27', id: 'cg27' },
  { title: 'charge28', content: 'chargeTest28', id: 'cg28' },
  { title: 'charge29', content: 'chargeTest29', id: 'cg29' },
  { title: 'charge30', content: 'chargeTest30', id: 'cg30' },
  { title: 'charge31', content: 'chargeTest31', id: 'cg31' },
  { title: 'charge32', content: 'chargeTest32', id: 'cg32' },

  { title: 'charge33', content: 'chargeTest33', id: 'cg33' },
  { title: 'charge34', content: 'chargeTest34', id: 'cg34' },
  { title: 'charge35', content: 'chargeTest35', id: 'cg35' },
];

export const whosfanList = [
  { title: 'whosfan1', content: 'whosfanTest1', id: 'wf1' },
  { title: 'whosfan2', content: 'whosfanTest2', id: 'wf2' },
  { title: 'whosfan3', content: 'whosfanTest3', id: 'wf3' },
  { title: 'whosfan4', content: 'whosfanTest4', id: 'wf4' },
  { title: 'whosfan5', content: 'whosfanTest5', id: 'wf5' },
  { title: 'whosfan6', content: 'whosfanTest6', id: 'wf6' },
  { title: 'whosfan7', content: 'whosfanTest7', id: 'wf7' },
  { title: 'whosfan8', content: 'whosfanTest8', id: 'wf8' },

  { title: 'whosfan9', content: 'whosfanTest9', id: 'wf9' },
  { title: 'whosfan10', content: 'whosfanTest10', id: 'wf10' },
  { title: 'whosfan11', content: 'whosfanTest11', id: 'wf11' },
  { title: 'whosfan12', content: 'whosfanTest12', id: 'wf12' },
  { title: 'whosfan13', content: 'whosfanTest13', id: 'wf13' },
  { title: 'whosfan14', content: 'whosfanTest14', id: 'wf14' },
  { title: 'whosfan15', content: 'whosfanTest15', id: 'wf15' },
  { title: 'whosfan16', content: 'whosfanTest16', id: 'wf16' },

  { title: 'whosfan17', content: 'whosfanTest17', id: 'wf17' },
  { title: 'whosfan18', content: 'whosfanTest18', id: 'wf18' },
  { title: 'whosfan19', content: 'whosfanTest19', id: 'wf19' },
  { title: 'whosfan20', content: 'whosfanTest20', id: 'wf20' },
  { title: 'whosfan21', content: 'whosfanTest21', id: 'wf21' },
  { title: 'whosfan22', content: 'whosfanTest22', id: 'wf22' },
  { title: 'whosfan23', content: 'whosfanTest23', id: 'wf23' },
  { title: 'whosfan24', content: 'whosfanTest24', id: 'wf24' },

  { title: 'whosfan25', content: 'whosfanTest25', id: 'wf25' },
  { title: 'whosfan26', content: 'whosfanTest26', id: 'wf26' },
  { title: 'whosfan27', content: 'whosfanTest27', id: 'wf27' },
  { title: 'whosfan28', content: 'whosfanTest28', id: 'wf28' },
  { title: 'whosfan29', content: 'whosfanTest29', id: 'wf29' },
  { title: 'whosfan30', content: 'whosfanTest30', id: 'wf30' },
  { title: 'whosfan31', content: 'whosfanTest31', id: 'wf31' },
  { title: 'whosfan32', content: 'whosfanTest32', id: 'wf32' },

  { title: 'whosfan33', content: 'whosfanTest33', id: 'wf33' },
  { title: 'whosfan34', content: 'whosfanTest34', id: 'wf34' },
  { title: 'whosfan35', content: 'whosfanTest35', id: 'wf35' },
];

export const awardsList = [
  { title: 'awards1', content: 'awardsTest1', id: 'aw1' },
  { title: 'awards2', content: 'awardsTest2', id: 'aw2' },
  { title: 'awards3', content: 'awardsTest3', id: 'aw3' },
  { title: 'awards4', content: 'awardsTest4', id: 'aw4' },
  { title: 'awards5', content: 'awardsTest5', id: 'aw5' },
  { title: 'awards6', content: 'awardsTest6', id: 'aw6' },
  { title: 'awards7', content: 'awardsTest7', id: 'aw7' },
  { title: 'awards8', content: 'awardsTest8', id: 'aw8' },

  { title: 'awards9', content: 'awardsTest9', id: 'aw9' },
  { title: 'awards10', content: 'awardsTest10', id: 'aw10' },
  { title: 'awards11', content: 'awardsTest11', id: 'aw11' },
  { title: 'awards12', content: 'awardsTest12', id: 'aw12' },
  { title: 'awards13', content: 'awardsTest13', id: 'aw13' },
  { title: 'awards14', content: 'awardsTest14', id: 'aw14' },
  { title: 'awards15', content: 'awardsTest15', id: 'aw15' },
  { title: 'awards16', content: 'awardsTest16', id: 'aw16' },

  { title: 'awards17', content: 'awardsTest17', id: 'aw17' },
  { title: 'awards18', content: 'awardsTest18', id: 'aw18' },
  { title: 'awards19', content: 'awardsTest19', id: 'aw19' },
  { title: 'awards20', content: 'awardsTest20', id: 'aw20' },
  { title: 'awards21', content: 'awardsTest21', id: 'aw21' },
  { title: 'awards22', content: 'awardsTest22', id: 'aw22' },
  { title: 'awards23', content: 'awardsTest23', id: 'aw23' },
  { title: 'awards24', content: 'awardsTest24', id: 'aw24' },

  { title: 'awards25', content: 'awardsTest25', id: 'aw25' },
  { title: 'awards26', content: 'awardsTest26', id: 'aw26' },
  { title: 'awards27', content: 'awardsTest27', id: 'aw27' },
  { title: 'awards28', content: 'awardsTest28', id: 'aw28' },
  { title: 'awards29', content: 'awardsTest29', id: 'aw29' },
  { title: 'awards30', content: 'awardsTest30', id: 'aw30' },
  { title: 'awards31', content: 'awardsTest31', id: 'aw31' },
  { title: 'awards32', content: 'awardsTest32', id: 'aw32' },

  { title: 'awards33', content: 'awardsTest33', id: 'aw33' },
  { title: 'awards34', content: 'awardsTest34', id: 'aw34' },
  { title: 'awards35', content: 'awardsTest35', id: 'aw35' },
];
