export const chartList = [
  { title: 'chart1', content: 'chartTest1' },
  { title: 'chart2', content: 'chartTest2' },
  { title: 'chart3', content: 'chartTest3' },
  { title: 'chart4', content: 'chartTest4' },
  { title: 'chart5', content: 'chartTest5' },
  { title: 'chart6', content: 'chartTest6' },
  { title: 'chart7', content: 'chartTest7' },
  { title: 'chart8', content: 'chartTest8' },

  { title: 'chart9', content: 'chartTest9' },
  { title: 'chart10', content: 'chartTest10' },
  { title: 'chart11', content: 'chartTest11' },
  { title: 'chart12', content: 'chartTest12' },
  { title: 'chart13', content: 'chartTest13' },
  { title: 'chart14', content: 'chartTest14' },
  { title: 'chart15', content: 'chartTest15' },
  { title: 'chart16', content: 'chartTest16' },

  { title: 'chart17', content: 'chartTest17' },
  { title: 'chart18', content: 'chartTest18' },
  { title: 'chart19', content: 'chartTest19' },
  { title: 'chart20', content: 'chartTest20' },
  { title: 'chart21', content: 'chartTest21' },
  { title: 'chart22', content: 'chartTest22' },
  { title: 'chart23', content: 'chartTest23' },
  { title: 'chart24', content: 'chartTest24' },

  { title: 'chart25', content: 'chartTest25' },
  { title: 'chart26', content: 'chartTest26' },
  { title: 'chart27', content: 'chartTest27' },
  { title: 'chart28', content: 'chartTest28' },
  { title: 'chart29', content: 'chartTest29' },
  { title: 'chart30', content: 'chartTest30' },
  { title: 'chart31', content: 'chartTest31' },
  { title: 'chart32', content: 'chartTest32' },

  { title: 'chart33', content: 'chartTest33' },
  { title: 'chart34', content: 'chartTest34' },
  { title: 'chart35', content: 'chartTest35' },
];

export const whookList = [
  { title: 'whook1', content: 'whookTest1' },
  { title: 'whook2', content: 'whookTest2' },
  { title: 'whook3', content: 'whookTest3' },
  { title: 'whook4', content: 'whookTest4' },
  { title: 'whook5', content: 'whookTest5' },
  { title: 'whook6', content: 'whookTest6' },
  { title: 'whook7', content: 'whookTest7' },
  { title: 'whook8', content: 'whookTest8' },

  { title: 'whook9', content: 'whookTest9' },
  { title: 'whook10', content: 'whookTest10' },
  { title: 'whook11', content: 'whookTest11' },
  { title: 'whook12', content: 'whookTest12' },
  { title: 'whook13', content: 'whookTest13' },
  { title: 'whook14', content: 'whookTest14' },
  { title: 'whook15', content: 'whookTest15' },
  { title: 'whook16', content: 'whookTest16' },

  { title: 'whook17', content: 'whookTest17' },
  { title: 'whook18', content: 'whookTest18' },
  { title: 'whook19', content: 'whookTest19' },
  { title: 'whook20', content: 'whookTest20' },
  { title: 'whook21', content: 'whookTest21' },
  { title: 'whook22', content: 'whookTest22' },
  { title: 'whook23', content: 'whookTest23' },
  { title: 'whook24', content: 'whookTest24' },

  { title: 'whook25', content: 'whookTest25' },
  { title: 'whook26', content: 'whookTest26' },
  { title: 'whook27', content: 'whookTest27' },
  { title: 'whook28', content: 'whookTest28' },
  { title: 'whook29', content: 'whookTest29' },
  { title: 'whook30', content: 'whookTest30' },
  { title: 'whook31', content: 'whookTest31' },
  { title: 'whook32', content: 'whookTest32' },

  { title: 'whook33', content: 'whookTest33' },
  { title: 'whook34', content: 'whookTest34' },
  { title: 'whook35', content: 'whookTest35' },
];

export const eventList = [
  { title: 'event1', content: 'eventTest1' },
  { title: 'event2', content: 'eventTest2' },
  { title: 'event3', content: 'eventTest3' },
  { title: 'event4', content: 'eventTest4' },
  { title: 'event5', content: 'eventTest5' },
  { title: 'event6', content: 'eventTest6' },
  { title: 'event7', content: 'eventTest7' },
  { title: 'event8', content: 'eventTest8' },

  { title: 'event9', content: 'eventTest9' },
  { title: 'event10', content: 'eventTest10' },
  { title: 'event11', content: 'eventTest11' },
  { title: 'event12', content: 'eventTest12' },
  { title: 'event13', content: 'eventTest13' },
  { title: 'event14', content: 'eventTest14' },
  { title: 'event15', content: 'eventTest15' },
  { title: 'event16', content: 'eventTest16' },

  { title: 'event17', content: 'eventTest17' },
  { title: 'event18', content: 'eventTest18' },
  { title: 'event19', content: 'eventTest19' },
  { title: 'event20', content: 'eventTest20' },
  { title: 'event21', content: 'eventTest21' },
  { title: 'event22', content: 'eventTest22' },
  { title: 'event23', content: 'eventTest23' },
  { title: 'event24', content: 'eventTest24' },

  { title: 'event25', content: 'eventTest25' },
  { title: 'event26', content: 'eventTest26' },
  { title: 'event27', content: 'eventTest27' },
  { title: 'event28', content: 'eventTest28' },
  { title: 'event29', content: 'eventTest29' },
  { title: 'event30', content: 'eventTest30' },
  { title: 'event31', content: 'eventTest31' },
  { title: 'event32', content: 'eventTest32' },

  { title: 'event33', content: 'eventTest33' },
  { title: 'event34', content: 'eventTest34' },
  { title: 'event35', content: 'eventTest35' },
];

export const newsList = [
  { title: 'news1', content: 'newsTest1' },
  { title: 'news2', content: 'newsTest2' },
  { title: 'news3', content: 'newsTest3' },
  { title: 'news4', content: 'newsTest4' },
  { title: 'news5', content: 'newsTest5' },
  { title: 'news6', content: 'newsTest6' },
  { title: 'news7', content: 'newsTest7' },
  { title: 'news8', content: 'newsTest8' },

  { title: 'news9', content: 'newsTest9' },
  { title: 'news10', content: 'newsTest10' },
  { title: 'news11', content: 'newsTest11' },
  { title: 'news12', content: 'newsTest12' },
  { title: 'news13', content: 'newsTest13' },
  { title: 'news14', content: 'newsTest14' },
  { title: 'news15', content: 'newsTest15' },
  { title: 'news16', content: 'newsTest16' },

  { title: 'news17', content: 'newsTest17' },
  { title: 'news18', content: 'newsTest18' },
  { title: 'news19', content: 'newsTest19' },
  { title: 'news20', content: 'newsTest20' },
  { title: 'news21', content: 'newsTest21' },
  { title: 'news22', content: 'newsTest22' },
  { title: 'news23', content: 'newsTest23' },
  { title: 'news24', content: 'newsTest24' },

  { title: 'news25', content: 'newsTest25' },
  { title: 'news26', content: 'newsTest26' },
  { title: 'news27', content: 'newsTest27' },
  { title: 'news28', content: 'newsTest28' },
  { title: 'news29', content: 'newsTest29' },
  { title: 'news30', content: 'newsTest30' },
  { title: 'news31', content: 'newsTest31' },
  { title: 'news32', content: 'newsTest32' },

  { title: 'news33', content: 'newsTest33' },
  { title: 'news34', content: 'newsTest34' },
  { title: 'news35', content: 'newsTest35' },
];

export const storeList = [
  { title: 'store1', content: 'storeTest1' },
  { title: 'store2', content: 'storeTest2' },
  { title: 'store3', content: 'storeTest3' },
  { title: 'store4', content: 'storeTest4' },
  { title: 'store5', content: 'storeTest5' },
  { title: 'store6', content: 'storeTest6' },
  { title: 'store7', content: 'storeTest7' },
  { title: 'store8', content: 'storeTest8' },

  { title: 'store9', content: 'storeTest9' },
  { title: 'store10', content: 'storeTest10' },
  { title: 'store11', content: 'storeTest11' },
  { title: 'store12', content: 'storeTest12' },
  { title: 'store13', content: 'storeTest13' },
  { title: 'store14', content: 'storeTest14' },
  { title: 'store15', content: 'storeTest15' },
  { title: 'store16', content: 'storeTest16' },

  { title: 'store17', content: 'storeTest17' },
  { title: 'store18', content: 'storeTest18' },
  { title: 'store19', content: 'storeTest19' },
  { title: 'store20', content: 'storeTest20' },
  { title: 'store21', content: 'storeTest21' },
  { title: 'store22', content: 'storeTest22' },
  { title: 'store23', content: 'storeTest23' },
  { title: 'store24', content: 'storeTest24' },

  { title: 'store25', content: 'storeTest25' },
  { title: 'store26', content: 'storeTest26' },
  { title: 'store27', content: 'storeTest27' },
  { title: 'store28', content: 'storeTest28' },
  { title: 'store29', content: 'storeTest29' },
  { title: 'store30', content: 'storeTest30' },
  { title: 'store31', content: 'storeTest31' },
  { title: 'store32', content: 'storeTest32' },

  { title: 'store33', content: 'storeTest33' },
  { title: 'store34', content: 'storeTest34' },
  { title: 'store35', content: 'storeTest35' },
];

export const chargeList = [
  { title: 'charge1', content: 'chargeTest1' },
  { title: 'charge2', content: 'chargeTest2' },
  { title: 'charge3', content: 'chargeTest3' },
  { title: 'charge4', content: 'chargeTest4' },
  { title: 'charge5', content: 'chargeTest5' },
  { title: 'charge6', content: 'chargeTest6' },
  { title: 'charge7', content: 'chargeTest7' },
  { title: 'charge8', content: 'chargeTest8' },

  { title: 'charge9', content: 'chargeTest9' },
  { title: 'charge10', content: 'chargeTest10' },
  { title: 'charge11', content: 'chargeTest11' },
  { title: 'charge12', content: 'chargeTest12' },
  { title: 'charge13', content: 'chargeTest13' },
  { title: 'charge14', content: 'chargeTest14' },
  { title: 'charge15', content: 'chargeTest15' },
  { title: 'charge16', content: 'chargeTest16' },

  { title: 'charge17', content: 'chargeTest17' },
  { title: 'charge18', content: 'chargeTest18' },
  { title: 'charge19', content: 'chargeTest19' },
  { title: 'charge20', content: 'chargeTest20' },
  { title: 'charge21', content: 'chargeTest21' },
  { title: 'charge22', content: 'chargeTest22' },
  { title: 'charge23', content: 'chargeTest23' },
  { title: 'charge24', content: 'chargeTest24' },

  { title: 'charge25', content: 'chargeTest25' },
  { title: 'charge26', content: 'chargeTest26' },
  { title: 'charge27', content: 'chargeTest27' },
  { title: 'charge28', content: 'chargeTest28' },
  { title: 'charge29', content: 'chargeTest29' },
  { title: 'charge30', content: 'chargeTest30' },
  { title: 'charge31', content: 'chargeTest31' },
  { title: 'charge32', content: 'chargeTest32' },

  { title: 'charge33', content: 'chargeTest33' },
  { title: 'charge34', content: 'chargeTest34' },
  { title: 'charge35', content: 'chargeTest35' },
];

export const whosfanList = [
  { title: 'whosfan1', content: 'whosfanTest1' },
  { title: 'whosfan2', content: 'whosfanTest2' },
  { title: 'whosfan3', content: 'whosfanTest3' },
  { title: 'whosfan4', content: 'whosfanTest4' },
  { title: 'whosfan5', content: 'whosfanTest5' },
  { title: 'whosfan6', content: 'whosfanTest6' },
  { title: 'whosfan7', content: 'whosfanTest7' },
  { title: 'whosfan8', content: 'whosfanTest8' },

  { title: 'whosfan9', content: 'whosfanTest9' },
  { title: 'whosfan10', content: 'whosfanTest10' },
  { title: 'whosfan11', content: 'whosfanTest11' },
  { title: 'whosfan12', content: 'whosfanTest12' },
  { title: 'whosfan13', content: 'whosfanTest13' },
  { title: 'whosfan14', content: 'whosfanTest14' },
  { title: 'whosfan15', content: 'whosfanTest15' },
  { title: 'whosfan16', content: 'whosfanTest16' },

  { title: 'whosfan17', content: 'whosfanTest17' },
  { title: 'whosfan18', content: 'whosfanTest18' },
  { title: 'whosfan19', content: 'whosfanTest19' },
  { title: 'whosfan20', content: 'whosfanTest20' },
  { title: 'whosfan21', content: 'whosfanTest21' },
  { title: 'whosfan22', content: 'whosfanTest22' },
  { title: 'whosfan23', content: 'whosfanTest23' },
  { title: 'whosfan24', content: 'whosfanTest24' },

  { title: 'whosfan25', content: 'whosfanTest25' },
  { title: 'whosfan26', content: 'whosfanTest26' },
  { title: 'whosfan27', content: 'whosfanTest27' },
  { title: 'whosfan28', content: 'whosfanTest28' },
  { title: 'whosfan29', content: 'whosfanTest29' },
  { title: 'whosfan30', content: 'whosfanTest30' },
  { title: 'whosfan31', content: 'whosfanTest31' },
  { title: 'whosfan32', content: 'whosfanTest32' },

  { title: 'whosfan33', content: 'whosfanTest33' },
  { title: 'whosfan34', content: 'whosfanTest34' },
  { title: 'whosfan35', content: 'whosfanTest35' },
];

export const awardsList = [
  { title: 'awards1', content: 'awardsTest1' },
  { title: 'awards2', content: 'awardsTest2' },
  { title: 'awards3', content: 'awardsTest3' },
  { title: 'awards4', content: 'awardsTest4' },
  { title: 'awards5', content: 'awardsTest5' },
  { title: 'awards6', content: 'awardsTest6' },
  { title: 'awards7', content: 'awardsTest7' },
  { title: 'awards8', content: 'awardsTest8' },

  { title: 'awards9', content: 'awardsTest9' },
  { title: 'awards10', content: 'awardsTest10' },
  { title: 'awards11', content: 'awardsTest11' },
  { title: 'awards12', content: 'awardsTest12' },
  { title: 'awards13', content: 'awardsTest13' },
  { title: 'awards14', content: 'awardsTest14' },
  { title: 'awards15', content: 'awardsTest15' },
  { title: 'awards16', content: 'awardsTest16' },

  { title: 'awards17', content: 'awardsTest17' },
  { title: 'awards18', content: 'awardsTest18' },
  { title: 'awards19', content: 'awardsTest19' },
  { title: 'awards20', content: 'awardsTest20' },
  { title: 'awards21', content: 'awardsTest21' },
  { title: 'awards22', content: 'awardsTest22' },
  { title: 'awards23', content: 'awardsTest23' },
  { title: 'awards24', content: 'awardsTest24' },

  { title: 'awards25', content: 'awardsTest25' },
  { title: 'awards26', content: 'awardsTest26' },
  { title: 'awards27', content: 'awardsTest27' },
  { title: 'awards28', content: 'awardsTest28' },
  { title: 'awards29', content: 'awardsTest29' },
  { title: 'awards30', content: 'awardsTest30' },
  { title: 'awards31', content: 'awardsTest31' },
  { title: 'awards32', content: 'awardsTest32' },

  { title: 'awards33', content: 'awardsTest33' },
  { title: 'awards34', content: 'awardsTest34' },
  { title: 'awards35', content: 'awardsTest35' },
];
